### ISSUE TITLE
Not reflected when writing poem over 500 characters.

### ISSUE THREAD

**Issue by pakutoma** [shikorism/tissue#1]
As in the picture, writing a sentence of 500 characters in the note column does not appear to be posted. (By the way even 499 characters were useless)
![default](https://user-images.githubusercontent.com/31642509/34485410-d729edde-f00d-11e7-83d7-5caa473fc40a.PNG)
If it does not seem to be a problem with the current HEAD, please close it.

**Comment by pakutoma** [comment]
I used google translation, so I am sorry if the sentences were wrong.

**Comment by shibafu528** [comment]
お手数おかけしたようですが、こちらのリポジトリでは日本語OKです。(私が日本語くらいしか書けないので…)

この問題は、noteのテキストが改行コードCR+LFであった場合に発生することが確認できました。
最新の開発版でも現象が確認されましたので、バリデーション前に改行コードをLFにする感じで対応しようと思います。

**Comment by pakutoma** [comment]
私のWindowsがお手数をおかけしたようで、申し訳ありません。
