### ISSUE TITLE
タグのサジェスト機能がほしい

### ISSUE THREAD

**Issue by aiwas** [shikorism/tissue#105]
検索性向上のためにも、もっとタグ付けを簡単に行える仕組みがほしい。

一案として、専用のリゾルバがあるものに関しては、例えば作者名をタイトルからパースしておいて、最初からタグ欄に入れておく、または専用のUIを置いて予測変換のごとく関連しそうなタグを表示しておくなど。
Komifloなどの商業サイトはともかく、pixivやニジエでは作者名部分が変わることも考えられるので、自動付加ではなくあくまでサジェスト程度にしたい。

**Comment by aiwas** [comment]
今気付きましたが #40 と一部重複してますね……すみません。
メタデータの正規化を進めるなら作者名なんかはそちらで検索できるようにして、タグは専らオカズの属性を表すのに使ったほうがよさそうですが、属性のサジェストは難しそうですね……

**Comment by eai04191** [comment]
~~ディープラーニングでエロ画像タグづけか！？~~

pixivから拾ってきた際はタグも拾ってワンクリックで付与可能とかはやりたさがある 🦆 

#40 のこともそうですし、そもそも1チェックイン1オカズのもろもろを変える話もあるのでここらの改修はだいぶ時間がかかりそう
