### ISSUE TITLE
名前に右横書き属性を持つ文字を設定すると意図しない表示になる？

### ISSUE THREAD

**Issue by aiwas** [shikorism/tissue#128]
#### 概要

不具合というほどのことでもないかもですが。

名前に右横書き属性を持つ文字を設定すると、タイムスタンプも同じ`<h5>`タグ内の文字列なため、

1. 先頭の名前部分が属性に従って右から配置される
2. タイムスタンプが（弱い左横書き属性なので？）左から順に配置される

という感じで倒置されてしまっているようです。

![arabic](https://user-images.githubusercontent.com/2174112/53979904-4c048880-4152-11e9-95e5-a3510a4ab21a.png)

ちなみに、右横書きに強制上書きする `U+202E | Right-to-left override (RLO)` を挿入してみたところ、よくわかりませんが微妙に表示が崩れました。

![u 202e_rlo](https://user-images.githubusercontent.com/2174112/53980158-f8df0580-4152-11e9-81ac-42450535f53b.png)

2番目は極端な例なのでともかく、何かしら対策がいるかなと思います<del>（将来的には中東のオタクも使うかもしれないので）</del>

##### 何も考えず `.text-dark` に `float:left` を付けた

![image](https://user-images.githubusercontent.com/2174112/53980940-f1b8f700-4154-11e9-9a3d-98e834363a94.png)

![image](https://user-images.githubusercontent.com/2174112/53980875-c33b1c00-4154-11e9-84a8-591edd3dfc7f.png)

なぜか float を効かせると方向属性はタイムスタンプまで影響しなくなるみたいです（謎）
あとは `<small>` 部分に `vertical-align:sub` とかすれば外見上はよくなりそうですが、2番目の方はそもそも名前入力の時点でバリデーションしたほうがよさそうですね……

#### 結論

- 名前のバリデーション時にアレそうな特殊文字を落とす
- もともと右横書き属性を持つ文字が含まれた場合、右に寄せられてしまうのでなんか対策する

自分で修正できるほどの能力がないため報告だけになります。すみません。

**Comment by eai04191** [comment]
表示については、RTL文字のあと文が右から読む時なのか左から読む文なのか判別できないために起きる問題のようです。

![image](https://user-images.githubusercontent.com/3516343/53983696-2760de80-415b-11e9-8f37-1d65ee2a5220.png)

名前の直後に`&rlm;`を挿入してここからは左から右だということを表せば良さそうです。

![2019-03-08_04-30-08_chrome](https://user-images.githubusercontent.com/3516343/53983715-35aefa80-415b-11e9-931a-d83f31a90673.png)

**Comment by shibafu528** [comment]
一般的なケースについては #159 で対策してみます。

RLOのような、もはや悪意しか感じないやつはどうしましょうかね。普通使わないだろということでバリデーションで弾くのは有りかなと思います。

**Comment by aiwas** [comment]
対応ありがとうございます。

個人的には、方向制御文字以外でも問題を起こしそうなものは割と積極的に弾いてしまっていいんじゃないかと思います。

**Comment by unarist** [comment]
bdi要素の出番のような気がします。

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

**Comment by aiwas** [comment]
`<bdi>`よさそうなんですが Chrome Android / WebView に対応してないんですね、これ……
使うなら代替として示されてる `<span dir="auto">` でしょうか。

**Comment by unarist** [comment]
その対応状況データは古い気もします。Safariでも使えてますし。

とはいえどちらでもよさそうです。

https://www.w3.org/International/articles/inline-bidi-markup/#html4markup

**Comment by aiwas** [comment]
確認したらAndroidの Chrome 72 でも普通にいけてました。
デスクトップ版Edgeはやはり非対応のようですが、まあ……

**Comment by shibafu528** [comment]
どっちにしようかなーという感じになっています。

Edgeは興味がないので見なかったことにしてもいいかなって気持ちも。(未来が決まってしまったしな？)

**Comment by aiwas** [comment]
Chrome/Firefoxがカバーできるならよりセマンティックな bdi でもいい気がしますね。
Tissueユーザーのアクセスがブラウザ別でわかればそれを根拠とすることができそうですが……

**Comment by shibafu528** [comment]
本番サーバの 2019/3/21 〜 2019/3/29 までの access.log のUAのuniqを取ったところ、IE/Edgeでアクセスしてきているホストは皆無でした。

PC Chrome, Android Chrome, iOS Safariがカバーできていれば十分そうです。
