### ISSUE TITLE
READMEにアセットビルドを追記する

### ISSUE THREAD

**Issue by hinaloe** [shikorism/tissue#130]
#125 でアセットが各開発環境でwebpackを走らせてやる必要が生まれたので`yarn && yarn dev`なりなんなりをREADMEに追記しよう……と思ったもののよく考えたらほかはすべてDockerで統一されてるのでこちらも同様に対応したいところ。
nodeのコンテナを追加する？

ところで本番デプロイ時のアセットビルドってどうしてるんですか？

………あっ 
https://social.mikutter.hachune.net/@shibafu528/101709458442748276

**Comment by shibafu528** [comment]
本番はDocker勉強する前に立てたので、ベッタベタのベアメタル環境です……。

私は単に既存のDockerfileにNode.jsとYarnのインストール操作を追記していいんじゃないかなぁと思っています。

**Comment by hinaloe** [comment]
同コンテナで実行する必要もないので `node:10-alpine` あたりのビルド用コンテナを持ってたほうがバージョン分けて上げやすいわけですが一方で操作の統一性としたらまとめちゃったほうがいいですよね 🤔
