### ISSUE TITLE
forkプロジェクトからのpull-reqでCIが走ってない

### ISSUE THREAD

**Issue by hinaloe** [shikorism/tissue#135]
![image](https://user-images.githubusercontent.com/5253290/53996378-8afb0400-417b-11e9-9c84-63f6f733fc4e.png)

**Comment by shibafu528** [comment]
PRでのCIはオプションだったんですね……。対応しました。

他に管理者側で行わないといけないアクションがあったら、教えてください。  
特に問題なければ、CIが走ったのが確認できたらcloseをお願いします。

**Comment by hinaloe** [comment]
ですね。次に飛んできたPRあたりで見てみましょう！（わたしが出すPRだとこっちでCI走らせてるのでチェックが出てしまって参考にならない）

**Comment by hinaloe** [comment]
大丈夫そう
