### ISSUE TITLE
めっちゃ縦長の画像をリンクに貼られると、そのまま表示されて鬱陶しい

### ISSUE THREAD

**Issue by shibafu528** [shikorism/tissue#137]
下記例示のように、極端に縦に長い画像をメタデータとして含むリンクをチェックインされると、何も制約をかけていないのでブラウザの表示領域をもっていかれてしまう。これはスマホだと影響がより大きい。

## 例示
https://ertona.net/@shibafu528/101716028907056678 をリンクに貼ってチェックインした時の表示

![image](https://user-images.githubusercontent.com/1352154/54043085-170a3b80-420f-11e9-8f3f-6491b27db3e3.png)

**Comment by eai04191** [comment]
どの実装方法にしても、レターボックスを許容するか否かは決める必要がありそうです。

![localhost_4545_user_eroi 1](https://user-images.githubusercontent.com/3516343/54046592-33f73c80-4218-11e9-8935-bc2ad2844ade.png)

![localhost_4545_user_eroi](https://user-images.githubusercontent.com/3516343/54046593-35286980-4218-11e9-8662-0cdaab8a59ce.png)

**Comment by shibafu528** [comment]
Issue立てた頃はレターボックスでいいかなぁ、むしろそれくらいしか頭の中に無い調子だったのですが、よくよく各種SNSを眺めると大抵は切り抜いてますね。

うーーーん、トリミング表示ですかねぇ。
