### ISSUE TITLE
アラートの削除は必要か

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#146]
![localhost_4545_user_eroi (2)](https://user-images.githubusercontent.com/3516343/54100864-fc4ce800-4403-11e9-883e-7abddf476564.png)

この `#status` についてです。

https://github.com/shikorism/tissue/blob/ddd2a05607488faf2a82a7063fcec1466f9a2cd7/resources/assets/js/app.js#L24-L28

で5秒後に閉じるようになってますが、これは必要な動作でしょうか。
要素が削除されるとその大きさの分、あとの要素が急に移動してユーザーの体験を損ないます。

例えばGitHubではリポジトリを削除したときのアラートには削除ボタンはありますが自動では消えません。

![github com_](https://user-images.githubusercontent.com/3516343/54101318-58b10700-4406-11e9-9900-a5b28b47089a.png)

削除するつもりで使用するならBootstrapのToastをつかうという選択肢もあります。
https://getbootstrap.com/docs/4.3/components/toasts/

**Comment by shibafu528** [comment]
必要性もなければ、実装した深い理由もないです……

**Comment by eai04191** [comment]
じゃあ削除するPRを出しておきます。
