### ISSUE TITLE
ActivityPubResolverでMastodonのProfileを解決した際の問題

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#157]
1. `summary` にHTMLが入っているのにhtml2textしていないためそのまま表示されてしまう。
2. `content` が存在しないため`summary`の後につけた`' | '`が不自然。
3. `attributedTo`が存在しないためタイトルを取得できない。

ref: https://shikorism.net/checkin/1621

**Comment by shibafu528** [comment]
これって `type` によって扱い分けるべきなんでしょうかね……？

ActivityPubの専門家の話が聞きたい感があります。

**Comment by eai04191** [comment]
ちょっと調べた限りではprofileもobjectを継承しているので、profileだからcontentがないわけと決まるわけではないみたいですね

**Comment by unarist** [comment]
https://www.w3.org/TR/activitypub/#actor-objects

> As the upstream vocabulary for ActivityPub, any applicable [ActivityStreams] property may be used on ActivityPub Actors. Some ActivityStreams properties are particularly worth highlighting to demonstrate how they are used in ActivityPub implementations.

とあるように、そこに記載があるものはまあそういう用途と期待していいと思いますが、objectに定義されているattributedToやcontentの存在も許容されている感じです。この辺自由度全振りみたいなやつなので…。

なんにせよsummaryがかたやプレーンテキスト、かたやHTMLで、分岐しないとどうしようもないですが、個人的にはリゾルバが対応していないものとしてOGPにフォールバックしたいところ。その仕組みは今のMetadataResolverにはありませんが…。

**Comment by unarist** [comment]
余談ですが、プロフィール画像やヘッダ画像でチェックインしたいって話はあるのかなと思いつつ、だからといってプロフィールページのURL使われると画像変更されたらどうしようもないですね。というかリンク切れしそう。

**Comment by unarist** [comment]
> なんにせよsummaryがかたやプレーンテキスト、かたやHTMLで、分岐しないとどうしようもない

今更これが気になって調べたが、これを根拠に成立してるんかなあ。。。（たしかにNoteにはnameがなくsummaryがプレーンテキスト）

https://www.w3.org/TR/activitystreams-core/#object
> The summary property should be used as a fallback text representation, possibly automatically generated by the publisher. If there is no name property, the summary property should not include markup, and should be short enough to be used as a reasonable text representation of the object.
