### ISSUE TITLE
チェックインに「いいね」を付けられるようにする

### ISSUE THREAD

**Issue by shibafu528** [shikorism/tissue#168]
やります、やっています。

4/10あたりまでに進捗なかったら背中を撃ってください。

## TODO
* [x] API /api/likes
* [x] いいねボタン (カウンターつき)
* [x] 自分のいいねを閲覧できるようにする

## アドバイスが欲しい事
* 他人のいいねリストは見えたほうがいいか？見えないほうがいいか？
* あるチェックインを誰がいいねしたか、一覧が見られるほうがいいか？不要か？

## 今のところやるつもりが無い事
* いいねの通知
  * そもそも通知とか仕込める準備がまるで無い

**Comment by MitarashiDango** [comment]
自分の「いいね」リストを他人に見せるかどうかは、チェックイン履歴同様にユーザー自身が選択（プライバシー設定で一律切り替えとか？）できるとよいかもしれない
ただし、その場合に「いいね」対象チェックインの投稿者からの見え方についてもあわせて検討する必要があるかも（チェックインしたユーザーだけ、誰が「いいね」したか見える or チェックインしたユーザーからは「非公開いいね(仮称)」として見える など)

**Comment by shibafu528** [comment]
見せるかどうかは自分で決められる、これで良さそうですね。これすき表明したい人もいるかもしれませんし。

困った時のTwitter方式ということで、チェックインユーザからいいねした人が見えるようにしたとしても、非公開でいいねしてる人が誰かは分からないということにしますか。
