### ISSUE TITLE
サムネイルを表示させない機能がほしい

### ISSUE THREAD

**Issue by takusun** [shikorism/tissue#169]
サムネイルがどんと出てしまうので、人を選びそうなオカズを貼るのは気が引けます。
非公開にして投稿してもサイトを賑わさないので。

**Comment by unarist** [comment]
タグミュートとかあるといいのかも？

**Comment by shibafu528** [comment]
投稿側で配慮するための機能は実装されたので、このissueはcloseします。

タグミュートも需要はありそうなので #298 にissue分けました。
