### ISSUE TITLE
Firefox on i3wm の環境でチェックインするとタグ入力の input が黒くなる

### ISSUE THREAD

**Issue by kb10uy** [shikorism/tissue#229]
![Screenshot from 2019-06-29 20-41-22](https://user-images.githubusercontent.com/2630080/60383646-8782e400-9aae-11e9-8020-359f80870c7e.png)

**Comment by kb10uy** [comment]
CSS の `prefers-color-scheme` プロパティ関係っぽさがあるので、この欄で使われる input だけ transparent にするのがよさそう。

**Comment by kb10uy** [comment]
バグじゃね?

**Comment by aiwas** [comment]
再現しました。Firefoxの配色設定に関係なく発生します。

ブラウザに問題がないのでOSの配色設定を疑ってみたところ、GTK+3のテーマを明るいものに変更(Qogir-dark から Qogir-light へ)したところ、解消しました。  
[私が使用しているテーマ](https://github.com/vinceliuice/Qogir-theme)の説明を見ると同様の問題の解決策が載っていました。

1. `about:config` を開く
2. 右クリックで設定値を新規作成。
    - タイプは文字列
    - 名前は `widget.content.gtk-theme-override`
    - 値は任意のライトテーマ？（おそらく何らかのダークテーマを使用しているはずなので、そのlightでよい）

さらに調べたところ、Firefoxのバグとして報告されていました。
>  [1283086 - Some form fields are black on Gtk3 dark themes]( https://bugzilla.mozilla.org/show_bug.cgi?id=1283086)

こちらでも上述の設定値を生やす方法が記載されています。

---

環境

OS: Arch Linux
WM: i3 4.16.1
Browser: Mozilla Firefox 67.0

**Comment by shibafu528** [comment]
@kb10uy (remind) Fx68以降では改善されていますか？

**Comment by kb10uy** [comment]
改善されていました。
