### ISSUE TITLE
すでに追加されているタグは見た目を変えてほしい

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#236]
`.badge-secondary` あたりに変えたほうがクリックしても追加されないことが分かりやすいと思います

## プレビュー

![image](https://user-images.githubusercontent.com/3516343/60643046-cfb65380-9e6c-11e9-9cc7-f930b51eb636.png)

**Comment by shibafu528** [comment]
わかる

現在のタグ一覧をどう伝えるか悩んで放置した節があります。ルートインスタンスのdataではなく、タグ入力用コンポーネントに完全に封印された状態になっているので……。

**Comment by shibafu528** [comment]
TagInputから変更後のタグセットを逐一busにemitすればいい気がしてきたのでやってみる
