### ISSUE TITLE
タグ検索した際、関連するタグに自分自身が出てくる

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#247]
![image](https://user-images.githubusercontent.com/3516343/62469015-53e45980-b7d2-11e9-9698-f1fe904cc190.png)

**Comment by shibafu528** [comment]
「関連するタグ」という呼び方で齟齬が発生しているかも……？

これは、ニコニコ動画で言うところの「[キーワードでタグ自体を検索する機能](https://www.nicovideo.jp/related_tag/%E3%82%AA%E3%83%8A%E3%83%8B%E3%83%BC)」の実装です。  
そのため、完全一致するタグも含まれて表示されるのは、仕様として意図している振る舞いとなります。
