### ISSUE TITLE
メタデータに使用する画像の大きさ

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#250]
いくつかのサイトから取得したデータはサムネイルサイズ・プレビューサイズ・オリジナルサイズなど画像の大きさを選べることがありますが、Tissue上で使用する大きさの指標がないのでどれを使用するかは各リゾルバでバラバラになっています。

使用に推奨する大きさが決めてあると便利そうです。

**Comment by shibafu528** [comment]
FacebookのOGP画像推奨サイズを参考として、縦1200pxくらいでどうでしょうか。

FBでは幅1080px以上推奨、Tissueは縦長で400pxの領域なので高密度ディスプレイ考慮で3倍くらいかな？とざっくり求めました。

適当な数値ではあるものの、実際これよりも大きな画像は回線を食い潰すだけなので、可能なら避けたほうが良さそうです。
