### ISSUE TITLE
DLsiteResolverで作成したメタデータのdescription にHTMLタグが含まれることがある

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#253]
https://shikorism.net/checkin/2280

`strip_tags `

そもそもメタデータのdescriptionはプレーンテキストであることを期待されているのでどこかで一括して`strip_tags`するべき？

**Comment by shibafu528** [comment]
MetadataResolverの裁量ということにしたいです。strip_tagsを全体にかけるのは破壊力が高いと思うので。
