### ISSUE TITLE
非ログイン状態でいいねしようとできてしまう

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#279]
❓

![image](https://user-images.githubusercontent.com/3516343/64557667-05038400-d37d-11e9-9eb6-d4467a0e7ef1.png)

いやそりゃできないのはそうなんですが、ウェブサービスとしては非ログイン状態でログインが必要な動作をしようとしたらログインを促すのが適切に思えます。

**Comment by shibafu528** [comment]
非ログインで操作ボタン出さなくても良くない？とも思ったんですが、なんかその辺のWebサイト見てたらだいたいログイン誘導されたので大人しくエラーハンドル書きます。

**Comment by eai04191** [comment]
同じオカズでチェックインボタンはログインになるのでそれと同じようにすれば問題ないと思います

**Comment by shibafu528** [comment]
Auth middlewareが勝手にリダイレクトまでやってるのでAjaxだと分からない……

**Comment by eai04191** [comment]
close?
