### ISSUE TITLE
空のタグがチェックインに追加されることがある

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#295]
# 問題

![image](https://user-images.githubusercontent.com/3516343/68426442-8182d980-01eb-11ea-8267-651235c770e2.png)

チェックインに空のタグが含まれることがある
リンク先が`/search/checkin?q=`のためクリックしても検索できない

# 再現手順

1. タグ入力欄でタグを確定する
1. 何らかの方法で半角スペースを挿入する。<kbd>Shift + Space</kbd>、コピペなど
1. その後ろでタグを確定する
1. チェックインする
1. チェックインに空のタグが含まれる

# 期待する動作

空のタグは含まれない

---

以前から確認されていましたが、最近目立つようになってきたのでIssueにあげておきます

**Comment by shibafu528** [comment]
まずは、サーバサイドで空タグは捨てるよう修正しようと思います。

**Comment by shibafu528** [comment]
フロント側でスペースだけで入力確定されてしまうこと、あります？こちらで再現ができていない……

**Comment by eai04191** [comment]
コメントを忘れてましたすいません。
スペースだけでタグが確定したことはありません。
タグの前後に不要なスペースがくっついたままtagValueとして連結・送信された結果、スペースが連続して空のタグが生まれていたので、サーバー側で弾く処理がされたならクローズしても問題ないと思います。
![image](https://user-images.githubusercontent.com/3516343/72097498-d95ecd80-335f-11ea-8ace-b9b571442855.png)

区切り文字として以外のスペースが混ざるのが気になるようならタグの追加時に`trim()`すればよさそうです。

**Comment by shibafu528** [comment]
> タグの前後に不要なスペースがくっついたままtagValueとして連結・送信された結果、スペースが連続して空のタグが生まれていたので、サーバー側で弾く処理がされたならクローズしても問題ないと思います。

なるほど、理解しました。

> 区切り文字として以外のスペースが混ざるのが気になるようならタグの追加時に`trim()`すればよさそうです。

気になるので直します。
