### ISSUE TITLE
WebShareTargetやブックマークレットを紹介するページ

### ISSUE THREAD

**Issue by unarist** [shikorism/tissue#302]
前に実装したWebShareTarget https://github.com/shikorism/tissue/pull/103 をサイト上で全く説明していないことを思いだしたので、ブックマークレット等とあわせて紹介するページを作ると、チェックイン時の手間を省けていいのではないでしょうか。

こんな感じの説明ページを作ってチェックイン画面からリンクするようなイメージ。

---

以下のブックマークレットを使うと、ブラウザで現在見ているページで簡単にチェックインすることができます。

```
javascript:location.href='https://shikorism.net/checkin?link='+encodeURIComponent(location.href)
```

また、[Web Share Target](https://www.chromestatus.com/feature/5662315307335680) に対応しているブラウザでは、他のWebサイトやアプリからURLを「共有」することができます。

* Android版 Google Chrome の場合
    * 画面下に出てくる「ホーム画面に Tissue を追加」、もしくは右上のメニューからインストール
    * 任意のアプリからURLを共有 → Tissue を選択 → チェックイン画面

※Web Share Target の仕様はまだドラフト段階で、今後仕様の変更により動かなくなる場合があります。

### 高度な使い方

チェックイン画面のURLにクエリパラメータを付加することで、各フィールドに値をセットした状態で開くことができます。

例: https://shikorism.net/checkin?date=1900/1/1&time=00:00&tags=blah+blur&link=hoge&note=piyo

**Comment by shibafu528** [comment]
確かに、チェックインが面倒で離脱する人はそれなりにいるはずなので少しでも楽な手段は教えたいすね……

**Comment by cormojs** [comment]
し、知らなかった……
