### ISSUE TITLE
タグの大文字と小文字を区別しないようにして欲しい

### ISSUE THREAD

**Issue by MitarashiDango** [shikorism/tissue#312]
現状の仕様だと、タグの表記揺れがあった際にタグ検索結果が期待した結果とならない場合がある。

例) 「mmd」と「MMD」がそれぞれ別のタグとして扱われるため、「mmd」で検索した場合に「MMD」でタグ付けされているチェックインがヒットしない。
この例の場合、上記二つのタグは同一の意味を持つため、どちらか一方のタグ文字列で検索した場合、もう一方も検索結果に含まれることが期待されると思われます。

**Comment by shibafu528** [comment]
お手軽にやるならILIKEかなあ……

**Comment by shibafu528** [comment]
DB上のデータおよび入力値としてはCase Sensitiveで処理、検索時のみCase Insensitiveで処理という感じで仕様検討中です。

あとは、検索においては英文字のCase以外に日本語の正規化とかも考えたほうがいいかな、まあどうしようかな……というのも考えています。
