### ISSUE TITLE
チェックインデータのインポート/エクスポート

### ISSUE THREAD

**Issue by shibafu528** [shikorism/tissue#319]
個人的な記録や他システムからの移行を検討する人がいるかもしれない。  
というか俺がTissueローンチ以前の3〜4年分の記録をインポートしたい。

インポートの実装にあたっては、Tissue外から取り込んだデータであるというフラグを付与するつもり。

エクスポートはやるならついでにどう？という程度。個人運営のサーバだけをマスターにするのは不安な人いると思うし、利用者自身の手元に取り戻せるのは正しいと思うので……。

まずどういうデータ形式にするのか決めないとね。

**Comment by shibafu528** [comment]
インポートについては、CSVのような単純な(そして処理を書くのは微妙にだるい)形式のサポートはマスト。Excelでチョイチョイっと列でも並べれば取り込める程度ならギリギリやる気出せるかもしれないが、所定のJSONに加工しろとか言われたら絶対やりたくないので。

個人的にSJIS-winとUTF-8の両方に対応したい。SJIS-winを受理しないCSV受付フォームは世の中を分かっていないという主義なので。

**Comment by shibafu528** [comment]
エクスポートは、CSVで受理する列編成はまあそのまま吐けるようにしておくとして、まっとうな構造化データスキーマは用意したいかも……？

**Comment by shibafu528** [comment]
## CSVインポート仕様
```yaml
ヘッダー行: 必須 (列名については「各列について」を参照)
対応文字コード:
  - UTF-8
    [TODO] UTF-8 with BOMに対応する必要はあるだろうか？Excelでこの形式は読めても書けなかったような...
  - SJIS-win (cp932)
各列について:
  日時:
    - この列は必ず含める必要がある
    - /^20\d{2}[-/](1[0-2]|0?\d)[-/](0?\d|[1-2]\d|3[01]) (0?\d|1\d|2[0-4]):(0?\d|[1-5]\d)(:(0?\d|[1-5]\d))?$/
    - 実在しない日付はエラー
    - 秒がついている場合、切り捨てて0秒として扱う
  ノート:
    - 500文字まで、複数行許可
  オカズリンク:
    - 2000文字まで
  タグ:
    - 500文字まで
    - 複数のタグを付ける場合、スペース区切りで記述する (チェックインPOST時の内部処理と同じ)
      [TODO] /^タグ\d+$/ みたいな列名でたくさん生やすのを許容したほうが取込用データを作成しやすいか？
```

## Example
```csv
日時,ノート,オカズリンク,タグ
2019-01-01 00:00,姫始め,http://example.com/,
2019-01-02 23:59,,,おっぱい MMD 弱音ハク
```

**Comment by shibafu528** [comment]
UTF-8以外の文字コードのファイルをCSVとして処理するのは、雑に全部読んでオンメモリにすればどうにでもなるけど、そうしないでうまいことやるには工夫がいるのでメモ。

https://hnw.hatenablog.com/entry/20090317

**Comment by shibafu528** [comment]
日付のセパレーターを複数種類受けるの、正規化する手間を惜しみたい気持ちが出てきた

**Comment by shibafu528** [comment]
日付セパレーター → 手間を惜しむことにした。yyyy/M/d で受理する。

**Comment by unarist** [comment]
`タグ\d+` って書いてるのにExampleは `タグ`（数字なし）でパターンにマッチしないような。
というか番号の並びまで気にしなくてもいいのではという気もするんですがどうでしょう。。

**Comment by shibafu528** [comment]
Exampleは仕様変更に追従させ忘れていたので直しました。

番号の並び……確かに気にしなくていいかもしれませんね。実装にあたっての希望要件として、タグは1つ1つを別々の列にしたいけど、名前がかぶっていると処理しづらくて困るというだけなので。

**Comment by shibafu528** [comment]
実装完了。
