### ISSUE TITLE
概要の時間をリセットしたい

### ISSUE THREAD

**Issue by MulticolorWorld** [shikorism/tissue#332]
特に長時間使わずに復帰した場合、平均記録と最長記録が意味をなさなくなってしまうので設定などから概要の時間がリセットできるとうれしい。

問題: 
- 記録や時間はいいとして通算チェックイン回数がリセットできるとタイムラインや被いいね数と齟齬が発生する可能性

**Comment by eai04191** [comment]
いちおう現時点で平均は直近30チェックインから出すようになっているので、長時間利用しなかったからと言って平均記録の意味が完全になくなるわけではないです
https://github.com/shikorism/tissue/pull/204
