### ISSUE TITLE
PixivResolverで使用してるプロキシが利用不能

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#337]
PixivResolverで使用していた`pixiv.cat`が利用不能になっているようです。
同サイトの提供するミラードメイン`pixiv.re`も利用できないことから、おそらくサービスを停止したようです。(ref: http://archive.is/KUf88)

## 対応案
1. pixivの画像を出すのをやめる
最も正しい。利用者が多いのでできれば避けたい
2. 自前でプロキシを用意する
    1. Cloudflare Workers
    幸い（おそらくpixiv.catの作者が）Cloudflare Workersで同じことを実装したもののソースが公開されています。
    アプリのAPIを叩くのでクレデンシャルが必要です。pixiv.catのAPIを使っているため修正が必要です
    https://github.com/pixiv-cat/pixivcat-cloudflare-workers
    pixivはCloudflareやGoogle Cloudの一部IPをブロックしているようなので失敗するかもしれません。回避するには結局別のサーバーが必要？
    2. nginx
    リファラを設定すればいいだけなのでnginxだけでできるようです。
    http://archive.is/t4Cja
3. ~~pixivにお願いして使わせてもらう~~

**Comment by shibafu528** [comment]
プロキシ復活しました。

> 由於本站所使用的DNS代管商(AWS Route53)未自動續費而在5月6日被暫停，造成本站DNS無法被解析，目前已切換至其他DNS代管商。

とのこと。

**Comment by eai04191** [comment]
よかった！

**Comment by eai04191** [comment]
今度はCloudflare、Host間の通信でInvalid SSL certificateで見れなくなっています。
Issueが建てられないようにOpenしておきます

**Comment by eai04191** [comment]
直ったので閉じておきます
