### ISSUE TITLE
チェックインの修正画面でエラーが発生すると新規チェックイン追加画面に移動してしまう

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#34]
チェックインの修正画面でエラー（noteが500文字以上など）を発生させると、新規チェックインの画面に移動します。

エラーを訂正してチェックインボタンを押すと、修正するチェックインと同じ日時の新規チェックインをしようとするため、エラーが発生します。

**Comment by shibafu528** [comment]
`fix/34` ブランチで修正したので確認お願いします。

**Comment by eai04191** [comment]
確認しました！大丈夫そうです！！
![screen shot 2019-01-17 at 01 00 24](https://user-images.githubusercontent.com/3516343/51261314-57a9bd80-19f3-11e9-89ec-194326f41724.png)
