### ISSUE TITLE
Bootstrapのビルド環境を整える

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#35]
今 `package.json` にあるのは過去に使おうとして放棄されているもの？

デザインをカスタマイズするにあたってsassはほぼ必須なのでビルド環境がほしい。

**Comment by shibafu528** [comment]
現在の `package.json` はLaravel 5.5のプロジェクトテンプレートにあったものがそのまま残っているだけだったかと思います。

現代的なモジュールバンドラーを使ったフロント開発まで進めるのだったら迷わずにwebpackを触ろうと思ったのですが、すぐにそこまでやるつもりも無いです。

gulpかParcelを導入してみましょうか。ちょっと考えてみます。
