### ISSUE TITLE
sans-serifフォントが指定されていないかつEmojiフォントがインストールされている場合、文字にEmojiフォントが使われることがある

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#395]
https://mstdn.maud.io/@reiden/104299310565266015
![image](https://user-images.githubusercontent.com/3516343/83955598-4d5dbd00-a88f-11ea-88a4-1a48148824f1.png)
https://mstdn.maud.io/@reiden/104299331055695270
https://mstdn.maud.io/@reiden/104299333025386212

Emojiフォントわざわざ入れてるような環境ならsans-serifの規定を指定しているはずとしてもよいですが、特にEmojiフォントを指定するメリットが今は無いはずなので、消しておくのもありだと思います。

**Comment by shibafu528** [comment]
こんな状態になってたら他のBootstrap使ってるWebサイトでも困りそうなものですが、どうして……

試しに消してみたら私の環境ではモノクロ絵文字になってしまったので、sans-serifからすべり落ちる環境のほうがヤバいので自己対処してくれということにしたいです。

**Comment by hinaloe** [comment]
これが数字以外で特定の言語研の文字で発生してたらロケールによっては有り得るけどっていう判断ができるけどこれは……
