### ISSUE TITLE
スペースを含むテキストをタグ入力欄にペーストしたあとタグ確定・チェックインすると、期待と異なるタグが登録される

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#414]
![2020-06-19_05-51-34](https://user-images.githubusercontent.com/3516343/85070586-048ff780-b1f1-11ea-8f06-3d2fcc9e37da.gif)

1. チェックイン画面でタグ入力欄にスペースを含むテキストをペーストする
2. `Enter`などでタグを確定する
3. この時点ではタグは半角スペースを含んでいるように見える
4. チェックインする
5. タグが半角スペースで分割されて記録されている

**Comment by hinaloe** [comment]
これってどういう挙動が理想？

1. UI上でスペースを代替文字(`_`など)に置換して表示、保存
1. UI上でスペースで分割したタグを表示、保存
1. その他

**Comment by eai04191** [comment]
2で考えてたけど、1のほうが求めているものっぽい
