### ISSUE TITLE
MetadataResolveService::execute()でトランザクションが使われていない

### ISSUE THREAD

**Issue by shibafu528** [shikorism/tissue#451]
MetadataResolveServiceでトランザクションが使われていないため、タグの保存中に例外が発生するとメタデータが失効するまで情報が半端に欠落した状態になる。

この辺とか:  
https://github.com/shikorism/tissue/blob/d69fe6a22a23eb685c4e04db84bb03f2c57311a1/app/Services/MetadataResolveService.php#L36-L48

メソッド内全体 `DB::transaction` にしちゃっても良い。(Springの`@Transactional`みたいなのあると楽なんだけどな、こういう時……!)

**Comment by hinaloe** [comment]
たしかにMiddlewareにしちゃってる人もいるな～（ぐぐったら知り合いの記事がでてくるシリーズ）

まあ雑に囲っとくのでもいいしどっちでもよさそう(?)
