### ISSUE TITLE
ニジエのページ指定をしたURLを登録するとエラーが発生する

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#56]
ニジエのページ指定したURL（作品のページから各ページのサムネイルに貼ってあるURL）をチェックインに登録すると、URL正規化(`App\Utilities\Formatter\normalizeUrl`)によって壊れたURLになります。

## 例
```
https://nijie.info/view_popup.php?id=296247&#diff_4
```
（ID296247の4ページ目）
これを正規化すると以下の様になります。

```
https://nijie.info/view_popup.php#diff_4?id=296247
```

このURLからは `HTTP 404` が返されサムネイルが取得できません。

**Comment by shibafu528** [comment]
URLの正規化処理に不具合がありました。修正をマージしたので、確認お願いします 🙇

**Comment by eai04191** [comment]
とりあえずサンプルのURLでは問題ないようです！
