### ISSUE TITLE
したらば掲示板から正しいメタデータが取得できない

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#61]
おそらくしたらば掲示板のエンコードがEUC-JPのため。

UTF-8でないページにも対応する必要がありそう。

**Comment by shibafu528** [comment]
https://github.com/shikorism/tissue/blob/bbbffcb39e563ba755f84cbec8cd3de19d262a18/app/MetadataResolver/OGPResolver.php#L20-L22

雑な変更案としては、ここの `mb_convert_string` の `$from_encoding` を `"ASCII,JIS,UTF-8,eucJP-win,SJIS-win""` あたりに変えたほうが良さそうですね。

あるいは、心を入れ替えてちゃんと判定を書くか……。

**Comment by eai04191** [comment]
とりあえずいま問題のものが直るなら雑変更でもアリだと思います。

判定するとしたら
- HTTPヘッダの `Content-Type `
- ソース内の `<meta>` タグ
- ソースを `mb_detect_encoding` に食わせる
とかになるんですかね。
文字コード周りは知見がないのでどれがいいのかわからないのですが……
