### ISSUE TITLE
スマホから閲覧すると、ユーザーページ下のページ番号が多いとはみ出る

### ISSUE THREAD

**Issue by moko256** [shikorism/tissue#68]
![toomanypage](https://i.imgur.com/J4Ikmu5.jpg)

**Comment by shibafu528** [comment]
Laravel標準のページネーションをちゃんと使ってないせいな気がしてきました。

ちゃんと使えば、全ページのリンクをドバーッと出すのではなく先頭、末尾、現在ページ近辺だけ出すみたいなの出来そう。

----
Memo: 

ページネーションテンプレートのカスタマイズが必要であれば、下記の方法で可能。  
別にしなくても、単純なものであればBootstrap 4用テンプレートは添付されている。Laravel 5.5時点ではデフォルトになっていないだけ。

https://readouble.com/laravel/5.5/ja/pagination.html#customizing-the-pagination-view

**Comment by moko256** [comment]
:pray:
