### ISSUE TITLE
Pixivリゾルバ mode=manga に対応していない

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#76]
pixivの`mode=`には
1. `medium` 作品ページ
2. `manga` 続きを見る 漫画ページ
3. `manga_big` 漫画ページから拡張ボタンを押したときに出る漫画の中の1枚のページ

がある。1と3には対応しているが2に対応していなかった。

**Comment by shibafu528** [comment]
これ、恐らくスクロールした所で動的にURLにページ情報が付与されるみたいなことは無いですよね？

そうであれば、`mode=medium` と同等として処理したらいいのかなと考えています。
