### ISSUE TITLE
メタデータのdescriptionに含まれる改行が無視されている

### ISSUE THREAD

**Issue by shibafu528** [shikorism/tissue#87]
## 理由
`$.text(value)` で設定してるから。

## 期待する動作
`description` 内の改行が表示上反映されること。

リゾルバでテキストを整形したい場合に、改行が使えないのは足枷であるように感じた。

## 実装案
1. CSSで [`white-space: pre`](https://developer.mozilla.org/ja/docs/Web/CSS/white-space) を当てる
2. JS上でnl2br的なことをする
    * これやるとinnerHTMLを扱うことになって、毒抜きが必要になりそう……？面倒そう。

## 懸念
現状のリゾルバは全て、改行が無視されることを前提としている (か、何も考えていない)。

意図しない表示、特に想定以上の改行が入っていたのが反映されて表示領域が極端に広がるなどがあるかもしれない。

**Comment by eai04191** [comment]
改行文字で改行してほしいなら、CSSで対応する場合は `pre-line` が適切に思えます。
`pre` や `pre-wrap` では連続した空白が表示されてしまうからです。
個人的にはCSSで対応する方法がいいと思います。

表示領域の懸念はカードかカードテキストに`max-height`を当ててあげれば問題なさそうです。
