### ISSUE TITLE
一部のTwitter URLのOGPが取得できない

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#887]
![image](https://user-images.githubusercontent.com/3516343/175830442-714493d4-fce1-4be6-bb6f-5e6a8731e52a.png)

twitterの投稿率は結構高いので対処するべき問題

公開チェックインを見たところ[2022/06/22 14:19](https://shikorism.net/checkin/33524)から[2022/06/23 21:37](https://shikorism.net/checkin/33561)の間に何かしらの変更があった模様

## 現在のUA

https://github.com/shikorism/tissue/blob/3ba82a635f4134020bd034a4cd96d0a3d15014c2/app/Providers/AppServiceProvider.php#L82-L85

---

![image](https://user-images.githubusercontent.com/3516343/175829862-db5888e2-445f-4881-92f1-5a8cc00b4589.png)

私の環境では現在のUAでOGPが取得できた

~~IPがBANされた？~~

**Comment by hinaloe** [comment]
SSR UA Hackが封じられたのかと思ったらそういうわけではなさそう

**Comment by eai04191** [comment]
- https://twitter.com/knr_am/status/1537019372262129664
- https://twitter.com/MDOCTKSCB/status/1540643240776695810
- https://twitter.com/oreizm/status/1520083522106535936

該当の投稿は「成人向け」とフラグされていた。これらに対するOGPを出力しなくなっているみたい

![image](https://user-images.githubusercontent.com/3516343/175829918-2e1343ba-dea2-49b4-bbda-2ebac30ce7e9.png)

**Comment by shibafu528** [comment]
他に手がなければTwitter APIのアプリケーション登録を行い、API経由で取得しようと思います。めんどいのであまり気は進まないけど、重要度は高いため……。
